biblioteca/src/br/com/biblioteca/model/Item.java
package br.com.biblioteca.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
public class Item {
	
	@Id // primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) // gerar ids automaticamente
	private Integer id;
	
	private Integer tipo;
	
	@NotEmpty // nao permitir campo nulo na aplicacao
	@Column(nullable = false) // nao permitir campo nulo na tabela
	private String descricao;
	
	@NotEmpty // nao permitir campo nulo na aplicacao
	@Column(name = "tipoaquisicao", nullable = false) // nao permitir campo nulo na tabela
	private String tipoAquisicao;
	
	@Column(name = "valorcompra") 
	private double valorCompra;
	
	@Column(name = "edespecial") 
	private boolean edEspecial;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTipo() {
		return tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descicao) {
		this.descricao = descicao;
	}

	public String getTipoAquisicao() {
		return tipoAquisicao;
	}

	public void setTipoAquisicao(String tipoAquisicao) {
		this.tipoAquisicao = tipoAquisicao;
	}

	public double getValorCompra() {
		return valorCompra;
	}

	public void setValorCompra(double valorCompra) {
		this.valorCompra = valorCompra;
	}

	public boolean isEdEspecial() {
		return edEspecial;
	}

	public void setEdEspecial(boolean edEspecial) {
		this.edEspecial = edEspecial;
	}
	
	/*
	 * Metodo para retornar o tipo de aquisicao de forma completa
	 * Se o tipo for D retorna Doacao
	 * Se o tipo for C retorna C
	 * Se não for nem C ou D retorna invalido
	 */
	public String getTipoAquisicaoToString() {
		if (tipoAquisicao.equals("C")) {
			return "Compra";
		} else if (tipoAquisicao.equals("D")) {
			return "Doação";
		} else {
			return "Tipo inválido";
		}
	}
	
	/*
	 * Metodo para retornar o tipo do item de forma completa
	 * Se o tipo for 0 retorna Livro
	 * Se o tipo for 1 retorna Revista
	 */
	public String getTipoToString() {
		if (tipo == 0) {
			return "Livro";
		} else {
			return "Revista";
		}
	}
}

biblioteca/src/br/com/biblioteca/web/controller/ItemController.java
package br.com.biblioteca.web.controller;

import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import br.com.biblioteca.dao.ItemDAO;
import br.com.biblioteca.model.Item;

@Controller
@RequestMapping("/item") // mapeia todas as requisicoes que comecem com /item
public class ItemController {
	
	/*
	 * Recebe a requisicao com mapeamento /item/novo
	 * Redireciona para a pagina novo.jsp na pasta item
	 * So ira utilizar o mapeamento se a requisicao for pelo metodo GET
	 */
	@RequestMapping(value = "/novo", method = RequestMethod.GET)
	public String novo() {
		return "/item/novo";		
	}
	
	/*
	 * Recebe a requisicao com mapeamento /item/salvar
	 * Inicia o tratamento para salvar um item no banco de dados
	 * So ira utilizar o mapeamento se a requisicao for pelo metodo POST
	 * @Valid valida o objeto item
	 * BindingResult permite verificar se algum erro de validacao foi encontrado no formulario
	 */
	@RequestMapping(value = "/salvar", method = RequestMethod.POST)
	public String salvar(@Valid Item item, BindingResult result) {
		// se algum erro for encontrado redireciona para a pagina do formulario
		if (result.hasErrors()) {
			return novo();
		}
		
		ItemDAO itemDAO = ItemDAO.getInstance(); // cria uma instancia da classe ItemDAO
		itemDAO.cadastraItem(item); // persiste o item no banco de dados
		
		return "/item/adicionado"; // redireciona para a pagina adicionada.jsp 
	}
	
	/*
	 * Recebe a requisicao com mapeamento /item/lista
	 * Inicia o tratamento para receber uma colecao de itens do banco de dados
	 * So ira utilizar o mapeamento se a requisicao for pelo metodo GET
	 */
	@RequestMapping(value = "/lista", method = RequestMethod.GET)
	public ModelAndView lista() {
		ItemDAO itemDAO = ItemDAO.getInstance(); // cria uma instancia da classe ItemDAO
		
		// cria um objeto da clase ModelAndView para adicionar parametros na pagina
		ModelAndView modelAndView = new ModelAndView("/item/lista");
		// adiciona a variavel items a colecao de itens do banco de dados
		modelAndView.addObject("items", itemDAO.getLista());
		
		return modelAndView;
	}
}

biblioteca/WebContent/WEB-INF/views/item/adicionado.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<tags:templateusuario title="Salvar Item">
	<jsp:body>
		<h1>Item adicionado com sucesso!</h1>
	</jsp:body>	
</tags:templateusuario>

biblioteca/WebContent/WEB-INF/views/item/lista.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<tags:templateusuario title="Listagem de itens">
	<jsp:body>
		<table>
			<tr>
				<th>ID</th>
				<th>Descrição</th>
				<th>Tipo</th>
				<th>Aquisição</th>
				<th>Valor compra</th>
				<th>Edição especial</th>
			</tr>
			<c:forEach items="${items }" var="item">
				<tr>
					<td>${item.id }</td>
					<td>${item.descricao }</td>
					<td>${item.tipoToString }
					<td>${item.tipoAquisicaoToString }
					<td>${item.valorCompra }</td>
					<td>${item.edEspecial ? 'Sim' : 'Não' }</td>
				</tr>
			</c:forEach>
		</table>
	</jsp:body>
</tags:templateusuario>